# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SLAMCamera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket' 

  # Pods for SLAMCamera

  target 'SLAMCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SLAMCameraUITests' do
    # Pods for testing
  end

end
